//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifetime_apd
{
    using System;
    using System.Collections.Generic;
    
    public partial class penerimaan
    {
        public int ID { get; set; }
        public Nullable<int> ID_APD { get; set; }
        public Nullable<int> ID_KARYAWAN { get; set; }
        public Nullable<System.DateTime> TANGGAL_PENERIMAAN { get; set; }
        public Nullable<int> TOTAL_PENERIMAAN { get; set; }
    
        public virtual apd apd { get; set; }
        public virtual karyawan karyawan { get; set; }
    }
}
