//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifetime_apd
{
    using System;
    using System.Collections.Generic;
    
    public partial class pengadaan
    {
        public int ID { get; set; }
        public Nullable<int> JUMLAH_PENGADAAN { get; set; }
        public Nullable<System.DateTime> TANGGAL_PENGADAAN { get; set; }
    }
}
