//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifetime_apd
{
    using System;
    using System.Collections.Generic;
    
    public partial class permintaan
    {
        public int ID { get; set; }
        public Nullable<int> ID_PERMINTAAN { get; set; }
        public Nullable<int> ID_KARYAWAN { get; set; }
        public Nullable<System.DateTime> TANGGAL_PERMINTAAN { get; set; }
        public Nullable<int> JUMLAH_PERMINTAAN { get; set; }
        public string STATUS_PERMINTAAN { get; set; }
    
        public virtual apd apd { get; set; }
        public virtual karyawan karyawan { get; set; }
    }
}
