//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifetime_apd
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.karyawans = new HashSet<karyawan>();
        }
    
        public int ID { get; set; }
        public string NAMA { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FOTO { get; set; }
        public Nullable<int> ID_UNIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<karyawan> karyawans { get; set; }
        public virtual unit unit { get; set; }
    }
}
